name: mobsfscan

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: mobsfscan
      uses: MobSF/mobsfscan@main
      with:
        args: '--type android --config config/config.mobsf --exit-warning android'
